algo = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(algo)}')
print(f'Só contem espaços? {algo.isspace()}')
print('É numérico? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print(f'É alfanumérico: {algo.isalnum()}')
print('Está minúsculo? {}'.format(algo.islower()))
print('Está maiúscUlo? {}'.format(algo.isupper()))
print(f'Está capitalizada? {algo.istitle()}')